import Formal.NavierStokesTimeBridge
import Formal.MildSolutionSemantics
import Formal.MildFlowMapBridge
import Formal.MildZeroUniqueness
import Formal.QuadraticMildNonlinearity
import Formal.QuadraticLinearizedMild
import Formal.ReducedBridgeResidual

/-
CI-visible axiom audit for the strongest currently formalized bridge theorems.

These commands do not add assumptions. They print the axiom dependencies of the declarations
into the Lean build log so that unexpected dependencies are visible during review.
-/
#print axioms MNS2.affine_flowmap_bridge_of_contDiffOn_open
#print axioms MNS2.radial_flowmap_bridge_of_contDiffOn_open
#print axioms MNS2.FixedTimePDEBridgeAdapter.affine_bridge
#print axioms MNS2.FixedTimePDEBridgeAdapter.radial_bridge
#print axioms MNS2.FixedTimePDEBridgeAdapter.radial_bridge_of_zero_fixed
#print axioms MNS2.NavierStokesTimeBridgeAdapter.affine_bridge_at_time
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_at_time
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_at_time_of_zero_fixed
#print axioms MNS2.MildEvolutionKernel.evolvesAt_nonnegative
#print axioms MNS2.MildEvolutionKernel.evolvesAt_zero_eq_initial
#print axioms MNS2.MildEvolutionKernel.evolvesAt_endpoint_equation
#print axioms MNS2.NavierStokesTimeBridgeAdapter.mild_endpoint_equation
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_path_has_mild_witness
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_eq_mild_duhamel
#print axioms MNS2.MildEvolutionKernel.trajectoryUniqueOn_endpointUniqueAt
#print axioms MNS2.MildEvolutionKernel.zero_isMildSolutionOn
#print axioms MNS2.MildEvolutionKernel.zero_evolvesAt_zero
#print axioms MNS2.NavierStokesTimeBridgeAdapter.stateMap_zero_of_mild_endpointUnique
#print axioms MNS2.NavierStokesTimeBridgeAdapter.stateMap_zero_of_mild_trajectoryUnique
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_eq_mild_duhamel_of_endpointUnique
#print axioms MNS2.hasFDerivAt_quadraticDiagonal
#print axioms MNS2.fderiv_quadraticDiagonal
#print axioms MNS2.MildEvolutionKernel.ofQuadratic_zero_evolvesAt_zero
#print axioms MNS2.quadraticLinearizedMild_equation_at_time_expanded
#print axioms MNS2.quadraticMildTangentEvolvesAt_nonnegative
#print axioms MNS2.quadraticMildTangentEvolvesAt_zero_eq_initial
#print axioms MNS2.quadraticMildTangent_zero_evolvesAt_zero
#print axioms MNS2.interval_integral_approximation_error_bound
#print axioms MNS2.radial_reduced_bridge_error_bound
#print axioms MNS2.radial_reduced_endpoint_error_bound_of_zero_fixed
