import Formal.NavierStokesTimeBridge
import Formal.FlowMapNonextendibilityCriterion
import Formal.UniformRestartContinuation
import Formal.TerminalFlowMapAmplification
import Formal.TerminalFlowMapOperatorNorm
import Formal.MildSolutionSemantics
import Formal.MildFlowMapBridge
import Formal.MildZeroUniqueness
import Formal.QuadraticMildNonlinearity
import Formal.QuadraticLinearizedMild
import Formal.QuadraticMildTangentAdapter
import Formal.QuadraticMildFixedPointDerivative
import Formal.QuadraticMildTangentRealization
import Formal.QuadraticMildCoherentFamilyAdapter
import Formal.LerayProjectedQuadratic
import Formal.R3LerayFrequencySymbol
import Formal.R3StokesFrequencySymbol
import Formal.R3StokesL2Operator
import Formal.R3LerayL2Operator
import Formal.R3SobolevCarrier
import Formal.ReducedBridgeResidual
import Formal.FiniteRankReducedBridge

/-
CI-visible axiom audit for the strongest currently formalized bridge theorems.

These commands do not add assumptions. They print the axiom dependencies of the declarations
into the Lean build log so that unexpected dependencies are visible during review.
-/
#print axioms MNS2.affine_flowmap_bridge_of_contDiffOn_open
#print axioms MNS2.radial_flowmap_bridge_of_contDiffOn_open
#print axioms MNS2.FixedTimePDEBridgeAdapter.affine_bridge
#print axioms MNS2.FixedTimePDEBridgeAdapter.radial_bridge
#print axioms MNS2.FixedTimePDEBridgeAdapter.radial_bridge_of_zero_fixed
#print axioms MNS2.NavierStokesTimeBridgeAdapter.affine_bridge_at_time
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_at_time
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_at_time_of_zero_fixed
#print axioms MNS2.FlowMapContinuationPackage.endpoint_norm_le_of_radial_directional_bound
#print axioms MNS2.FlowMapContinuationPackage.directional_fderiv_unbounded_of_nonextendible
#print axioms MNS2.FlowMapUniformRestartPackage.continuation_of_uniform_endpoint_bound
#print axioms MNS2.FlowMapUniformRestartPackage.directional_fderiv_unbounded_of_nonextendible
#print axioms MNS2.FlowMapUniformRestartPackage.terminal_directional_fderiv_unbounded_of_nonextendible
#print axioms MNS2.FlowMapUniformRestartPackage.eventually_arbitrarily_large_directional_fderiv
#print axioms MNS2.FlowMapUniformRestartPackage.terminal_fderiv_opNorm_unbounded_of_nonextendible
#print axioms MNS2.FlowMapUniformRestartPackage.exists_terminal_fderiv_opNorm_above
#print axioms MNS2.MildEvolutionKernel.evolvesAt_nonnegative
#print axioms MNS2.MildEvolutionKernel.evolvesAt_zero_eq_initial
#print axioms MNS2.MildEvolutionKernel.evolvesAt_endpoint_equation
#print axioms MNS2.NavierStokesTimeBridgeAdapter.mild_endpoint_equation
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_path_has_mild_witness
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_eq_mild_duhamel
#print axioms MNS2.MildEvolutionKernel.trajectoryUniqueOn_endpointUniqueAt
#print axioms MNS2.MildEvolutionKernel.zero_isMildSolutionOn
#print axioms MNS2.MildEvolutionKernel.zero_evolvesAt_zero
#print axioms MNS2.NavierStokesTimeBridgeAdapter.stateMap_zero_of_mild_endpointUnique
#print axioms MNS2.NavierStokesTimeBridgeAdapter.stateMap_zero_of_mild_trajectoryUnique
#print axioms MNS2.NavierStokesTimeBridgeAdapter.radial_bridge_eq_mild_duhamel_of_endpointUnique
#print axioms MNS2.hasFDerivAt_quadraticDiagonal
#print axioms MNS2.fderiv_quadraticDiagonal
#print axioms MNS2.MildEvolutionKernel.ofQuadratic_zero_evolvesAt_zero
#print axioms MNS2.quadraticLinearizedMild_equation_at_time_expanded
#print axioms MNS2.quadraticMildTangentEvolvesAt_nonnegative
#print axioms MNS2.quadraticMildTangentEvolvesAt_zero_eq_initial
#print axioms MNS2.quadraticMildTangent_zero_evolvesAt_zero
#print axioms MNS2.QuadraticMildC1TangentAdapter.fderiv_realizes_linearized_mild
#print axioms MNS2.QuadraticMildC1TangentAdapter.radial_bridge_with_linearized_mild_semantics
#print axioms MNS2.QuadraticMildC1TangentAdapter.radial_endpoint_bridge_with_linearized_mild_semantics
#print axioms MNS2.quadraticMild_fixedPoint_fderiv_eq_of_dominated
#print axioms MNS2.quadraticMild_fixedPoint_fderiv_apply_eq_of_dominated
#print axioms MNS2.quadraticMild_fixedPoint_fderiv_eq_of_dominated_on_nhds
#print axioms MNS2.quadraticMild_fixedPoint_fderiv_apply_eq_of_dominated_on_nhds
#print axioms MNS2.quadraticMildRHSDerivativeAtTime_apply_eq_linearized
#print axioms MNS2.quadraticMild_fixedPoint_direction_equation_of_certificate
#print axioms MNS2.quadraticMild_fixedPoint_direction_equation_of_local_certificate
#print axioms MNS2.quadraticMildTangentEvolvesAt_of_dominated_fixedPoint_family
#print axioms MNS2.quadraticMildTangentEvolvesAt_of_local_fixedPoint_family
#print axioms MNS2.QuadraticMildC1CoherentFamilyAdapter.fderiv_realizes_linearized_mild
#print axioms MNS2.QuadraticMildC1CoherentFamilyAdapter.radial_bridge_with_derived_tangent_semantics
#print axioms MNS2.LerayProjectedQuadraticContract.leray_idempotent_apply
#print axioms MNS2.LerayProjectedQuadraticContract.projectedConvection_mem
#print axioms MNS2.LerayProjectedQuadraticContract.quadraticDerivative_mem
#print axioms MNS2.LerayProjectedQuadraticContract.fderiv_mildKernel_nonlinearity_mem
#print axioms MNS2.mem_r3SolenoidalFiber_iff_inner
#print axioms MNS2.r3LeraySymbol_mem
#print axioms MNS2.inner_r3LeraySymbol_eq_zero
#print axioms MNS2.r3LeraySymbol_idempotent
#print axioms MNS2.norm_r3LeraySymbol_le
#print axioms MNS2.r3LeraySymbol_zero
#print axioms MNS2.r3LeraySymbol_self
#print axioms MNS2.r3LeraySymbol_apply
#print axioms MNS2.r3StokesDecayRate_nonneg
#print axioms MNS2.r3StokesScalar_le_one
#print axioms MNS2.r3StokesFrequencySymbol_zero_time
#print axioms MNS2.r3StokesFrequencySymbol_add_time
#print axioms MNS2.r3StokesFrequencySymbol_mem
#print axioms MNS2.r3StokesFrequencySymbol_commutes_leray
#print axioms MNS2.norm_r3StokesFrequencySymbol_le
#print axioms MNS2.r3StokesLerayFrequencySymbol_mem
#print axioms MNS2.continuous_r3StokesScalarComplex
#print axioms MNS2.norm_r3StokesScalarComplex_le_one
#print axioms MNS2.r3StokesL2FrequencyMultiplier_ae
#print axioms MNS2.fourier_r3StokesL2Operator
#print axioms MNS2.r3StokesL2FrequencyMultiplier_zero_time
#print axioms MNS2.r3StokesL2Operator_zero_time
#print axioms MNS2.r3LerayL2Operator_mem_solenoidal
#print axioms MNS2.r3NormalizedDivergenceL2OperatorAux_r3LerayL2Operator
#print axioms MNS2.r3LerayL2Operator_fixed_of_mem
#print axioms MNS2.r3LerayL2Operator_idempotent
#print axioms MNS2.norm_r3LerayL2Operator_apply_le
#print axioms MNS2.norm_r3LerayL2Operator_le_one
#print axioms MNS2.besselPotential_r3HsToTempered_eq_coordinate
#print axioms MNS2.r3HsToTempered_memSobolev
#print axioms MNS2.r3HmToTempered_memSobolev
#print axioms MNS2.r3StrongSobolevOrder_three
#print axioms MNS2.interval_integral_approximation_error_bound
#print axioms MNS2.radial_reduced_bridge_error_bound
#print axioms MNS2.radial_reduced_endpoint_error_bound_of_zero_fixed
#print axioms MNS2.intervalIntegral_finiteRankPath
#print axioms MNS2.radial_finiteRank_bridge_error_bound
#print axioms MNS2.radial_finiteRank_endpoint_error_bound_of_zero_fixed